version: '3.1'
services:
  storage:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Storage_Service
    depends_on:
      - storage-db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_DB=jdbc:postgresql://storage-db:5432/storage_db
      - DB_HOST=db
      - DB_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
  storage-db:
    image: postgres:14-alpine
    container_name: Storage_Db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/dataStorage

    environment:
      - POSTGRES_DB=storage_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
