server:
  port: 8080
  error:
      whitelabel:
        enabled: false
spring:
  mvc:
    throw-exception-if-no-handler-found:true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always
  datasource:
    url: ${SPRING_DATASOURCE_DB:jdbc:postgresql://localhost:5432/storage_db}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        orm:
          jpa: INFO
        transaction: INFO
    org.springframework:
      transaction:
        interceptor: TRACE
      orm:
        jpa:
          JpaTransactionManager: DEBUG

